# GitHub Release configuration
# This helps GitHub auto-generate release notes

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bug
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🧰 Maintenance
      labels:
        - chore
        - maintenance
    - title: Other Changes
      labels:
        - "*"